#+DESCRIPTION: A summary of this book
#+TITLE: The Labour Party - A Marxist History
* Running themes
Reform or revolution

Separation of politics and economics 

Running the state more efficiently

The LP is a supporter of the state - even at the cost of votes

* Actors
** AH - Arthur Henderson

Leader of the party after MacDonald's removal due to his lack of enthusiasm for WWI
** BCP - British Communist Party

Founded in 1921 - supported Lenin and the Soviets
** LP - Labour Party
* 1. The birth of reformism
** The precursors: from Chartists to the Independent Labour Party
1. The LP has always separated politics from trade unionism, unlike the Chartists
2. After the failure of the 1842 general strike, the 1848 revolutions, and a subsequent economic boom,
   the working class grew more quiescent, to the extent they could start to be trusted with the vote in 1867
3. The first Labour MPs were elected in the 1870s, however these were working class people standing as Liberals
4. As Engels predicted, growth of US power caused the economic boom to falter later in the century
** From New Unionism to reformist politics
New general unions emerged in the late 1880s - these rejected the separation of politics and economics, older unions
were for more highly skilled workers in specific crafts. These unions recognised that strikes weren't enough, however
the support for revolution over reform was weak

The new unions were quickly weakened - capitalists fought back with lockdowns, the older unions obstructed, and the
Marxist SDF was 'incurably sectarian'. To protect their union machinery, new union leaders moved right

Bradford, which had suffered some of the greatest new union defeats, became the heart of the reformist movement.

The increase in miltancy, even although defeated, together with increasing economic problems, led to the breakdown of
Lib-Lab-ism laid the groundwork for the ILP
** The Independent Labour Party
Was founded in Bradford in 1893. It's aim was socialism, however explicitly via reformism and
electoralism

Initially it had no members, just affiliations

It was formed from the new union leadership, which although had moved to bureaucratism, were still
advanced in comparison with the old unions
** The myth of the Golden Age

The LP was never anything but reformist - despite later mythology presenting the party
as having fallen from grace
** The Dependent Labour Party

Reformism, having rejected Marxism, has no intellectual tradition. They
    'seek[] to channel working class aspirations in an ideological framework set by the system'

The ILP talked of smoothing over class conflict - they imagined that the rich would welcome socialism, as
they couldn't enjoy their riches while the working class was in misery.

Both Hardie and MacDonald turned to Labour only after rejection from the Liberals. Even so Hardie maintained
his support for them
** 'The worst enemies of social revolution'

The Fabians, in particular Beatrice and Sydney Webb, became the intellectual backbone
of the LP. Unfortunately they despised the WC. They supported eugenics, and opposed health
insurance.

Two influences were
    - Joseph Chamberlain's 'gospen of ransom' - i.e. get the WC just enough that they don't revolt
    - An ending of lassez faire - as Germany and the US became more powerful capitalists wanted
      the state to intervene

Their aims were to organize capitalist production at the state level. This would require no input from
the WC.

Lenin correctly said 'the LP is a thoroughly bourgeois party'
* 2. Out of the bowels of the TUC
** A background of defeat and passivity

By the late 1890s the old unions had recovered power. They were at first vehemently opposed to the
ILP, yet 5 years later they created the LP

Capitalists battered unions into submission, using the courts to establish the Taff-Vale decision, which made
strikers liable for lost profits. At the same time union bureacracy strengthened as membership increased, and
unions worked with employers via conciliation schemes.

Eventually the bureacracy realised they would struggle to justify their existence, and in their own interests
moved into politics

[For all its weaknesses, the ILP was born of an advanced LW movement - the LP was a step backward]
** The foundation conference creates a 'Labour Alliance'

The 1899 TUC called for a special congress to look into increaing the number of labour MPs
This congress created the LRC, which became the LP

The Marxist SDF wanted a completely separate party, recognizing class war and aiming for socialism
The right essentially wanted to continue Lib-Labism

Keir Hardie propsed a group having their own whips, with no marked political differences

The LP was created top-down, and initially the WC took little notice. They did poorly in the 1990 election,
electing just two MPs - uncluding Hardie. The ILP ran 10 candidates without victory.
** The political expression of the trade union bureaucracy

The LRC caused unions to begin to detach from the Liberals

Unions who affiliated did so cause they wanted to get into parliament. The coal and
cotton unions were last as due to geographical concentration they could ensure Lib-Lab MPs
were elected

Taff-Vale encouraged more unions to move into politics at the same time as they retreated from strike
action.

Although the LRC was created from the link between economics and politics, it sought to separate the two - while
maintaining some union attitudes. Just as unions don't really care about their members political beliefs as long
as they pay dues, the LP wanted workers votes regardless of their politics.
** The problem of false consciousness

The LP came about from a number of false beliefs

- that economics and politics can be separated
- they could reject class war and take a common-sense approach
- there is a community interest shared by all classes
** A technical division of labour

If the unions are once removed from class struggle, as they seek to bridge
the gap between workers and bosses, the LP is twice removed as it seeks the
votes of an electorate that is largely not union members.

Despite recommendations from union leaders, the LP did poorly even in heavily
unionised areas

It was for this reason that Bevin described the LP as being 'born out of the bowels of the TUC'
** Denying class in a class society

The LP is an uneasy combination of being very close to the unions, while seeking to appeal
to the nation.

The LRC initially had little or no policies of its own, instead generally supporting the Liberals.

Hardie wrote to several prominent Liberals to see if they would lead Labour - to no avail

MacDonald and Galdstone made a secret deal to not compete against each other
** Significance

The birth of Labour was a mixed blessing.
It was an advance on Lib-Labism, however it sought no political advance at the base.
As such it sacrificed the socialist ideals of the left wing as it looked to appeal to all classes.
** The impact of parliament

In 1906 29 MPs were sent to parliament.

At first they were struck with the lack of power - the inability to move the machinery of parliament.
They were also awestruck at meeting famous politicians, and being treated as equals by them
** Taming conference

The PLP was formed almost immediately. The 1907 conference gave MPs the freedom
to ignore conference - the first wording was too explicit, however there was no
change in meaning in the final version

They did manage to referse Taff-Vale, albeit relucantly and with the help of the
Liberals
** Poodles of Liberalism

By 1910 the number of MPs had grown to 42 - helped by the affiliation of the miners.

In 1910 they supported a minority Liberal government, and as in the 1906-10 parliament, they almost always
voted alongside them. MacDonald considered merging with the Liberals.

The support for the Liberals descended into farce when MacDonald scuttled his own motion, which was in effect
a motion of censure, when it seemed it might win.
** Left alternatives

The poor performance of the LP in these parliaments led to two reactions on the left
- mass militancy, i.e. a rejection of parliamentary methods
- the 'eternal' left - pushing the LP to accept more radical policies. 'eternal' because
  reformist policies always involve compromise with capitalism 

Hardie, MacDonald and others resigned en mass from the ILP at the next vote that went against
them

MacDonald saw parliament as more important than the plight of the WC. This was exactly opposite
to Lenin's view that parliamentary activity as the lowest form of the workers movement.
** The outside left


Syndicalists recognized the inadequacy of parliament

The LP emerged from Liberalism due to the the union unrest beginning in 1910.
Union membership doubled, there were several national strikes, and clashes with police.
** A brake on the movement

The LP wasn't consulted over any union action. It frequently spoke against
atrikes, describing parliamentary activity as the only was for socialism, and even as
being truly revolutionary.

Labour MPs proposed a bill making it illegal to strike without going through a 30 day
conciliation process. The punishments were draconian fines. The TUC caused it to be dropped

In 1913 the LP and unions reconciled in their opposition to the miners strike. They were both
at risk from syndicalism. However syndicalism had no policies besides strikes for better pay/conditions.
* 3. War and reconstruction: Labour adopts socialism
** An early casualty of the fighting

MacDonald was replaced by Henderson after expressing doubts about the war

In 1915 the LP joined Asquith's coalition

Internationalism was abandoned, and workers leaders supported the war
** Moralism and Labour politics

Hardie discussed the idea of a general strike to prevent war, this was
defeated by the unions, making a rare foray into politics.

Internationalism was viewsed as a 'nice to have' by reformists, but expendable

The ILP remained opposed to the war, even after the coalition.
** The meaning of the split

The ILP opposed the war, as did Hardie, MacDonald and Snowden. Unions succumbed to patriotic hysteria - this was
an occasion when crisis allowed the union bureaucracy to impose its wishes
** The diverse attitudes to war

Pro-war views within the LP were extreme. ILP opponents were hounded, a mahjority of
objectors who were tries were ILP members.

The LP, unlike the SPD in Germany, didn't break up. This was because the bulk of its
support came from the unions, and so could absorb the range of opinions the unions had.
** The limits of the ILP position

The position of LP opponents to the war was based on the inefficiency of war - they viewed it
as a failing of diplomacy. By contrast Lenin viewed war as an inevitable consequence of capitalist
and imperialist competition

** Clydeside: the legend and the reality

A myth has grown connecting the Clyde Workers Committee and the Labour MPs
elected in 1922

Although there were strikes by the Clyde engineers, these weren't anti-war

** The triumph of statism

As a result of the war, the state took over most production. In return for their suspending rules on
working conditions, the union leadership began to work directly with the government

The upper reaches of the labour movement were absorbed by the state

** Reconstructing the party

Revolutionaries had grown in number as the LP collaborated during the war - these held
no truck with the LP. Discontent grew, and the 1917 revolution concentrated the LP's mind.

** 'Uncle Arthur' - apostle of Labour's socialist conversion

Lloyd George sent Arthur Henderson to Russia to bolster Russian support for the war.
He was horrified by what he saw, in particulae the elevation of workers over directors.

Fearing the return of large numbers of radicalised troops, skilled with arms, he looked
to Sidney Webb to help safeguard against "Bolshevism" via a strong parliamentary LP.

** The 1918 constitution: a quest for the 'people's party'

Henderson and Webb looked to reorganise the party so that it would speak for the
nation rather than the WC. Given over 90% of the party was affiliated trade unions
it was difficult to present this as beyond class.

The 1918 constitution created local Labour parties and individual membership

The ILP was sidelined as punishment for its pacifism

** Socialism at last

Webb and Henderson created Clause Four as a conscious attempt to fend off
revolution

At previous conferences attempts to write socialism into the constitution generally failed,
as even socialists feared the LP would lose votes if they did

Contradictory motions were allowed, even at the same conference - so it was no more than lip service

** Labour's new social order

This document called for a legal minimum wage, welfare provision, and other social improvements.

This was a logical consequence of their belief that suffering was an _unnecessary_ consequence
of capitalism.

The wide state power exerted during the war led them to believe in this

** Social reconstruction and nationalisation

The LP sought to manage capitalism through widespread nationalisation

This wasn't a particularly left-wing POV at the time, and in no way suggested
workers would actually be in control

Nationalisation would cement the power the unions had gained during WWI

Finally, it suited the reformist aim of piecemeal takeover of industry, but as Marks said, this would be
".. a reformation within the boundaries set by the bourgeoisie"

* 4. Riding the post-war storm
** Did Labour prevent a British revolution?


In 1918 there were revolutionary outbreaks in Finland, Germany, Austria, Hungary and Bavaria
In all cases social democrats used 'socialism' as a fig-leaf for obsrtuction

AH openly claimed that the LP calmed revolutionary spirit - however this isn't correct, the
advanced workers largely ignored the LP
** The shifting centre of gravity

Although the LP did poorly in the 1918 election in terms of seats, and while it added
its voice to the anti-Bolshevik chorus, it was innefective in stopping the very great numbers of strikes
that occurred at this time.

The centre of power had shifted to the unions. The LP still played an importnat role as an alibi for
the unions
** Three disputes

In the Clydeside engineers strike for a 40 hour week the ILP tried to restrain the strikers

The miners and railwaymen struck for nationalisation, an 80% wage rise and 2 hour working day reduction.
Nationalisation was the problem - in a meeting with Lloyd George he told them they would win, but where they
prepared to take over the function of the state. They were not and opted for a commission of enquiry.

Similarly the leadership of the railwaymen brought their strike to an end in 9 days

Although the LP and ILP were largely irrelevant - for example their papers didn't even have industrial correspondents,
however their body of reformist ideas gave authority to the unions' brakes
** Direct action - threat or opportunity?

Although there was talk at this time of direct action, the counter-arguments won. After all,
what was the point of the LP if we don't acheive reform constitutionally?
** Labour's most daring hour

Lloyd George called for British troops to back the Poles against Russia - this one time the LP
supported calls for a general strike against this
** Black Friday - the transition to a governing party

At times betraying the revolutionary left can raise support for reformism - as there
is no other option

In 1921, an agreemet between railwaymen, transport workers and miners broke down when the colliery
owners demanded a 50% pay cut. Labour offered no support, and in fact criticised those who expected
unemployment benefits.

Despite this - union membership suffered, and as support for direct action eroded, it transferred to the LP
** The swing of the pendulum

As union membership plummeted, the vote for the LP in the 1922 election doubled on 1918.

A separation occured between the LP and the unions, with the latter losing or giving up their
authority and positions within the LP.

* 5. Proving Labour 'fit to govern': the 1924 administration

Reformists see no contadiction between WC interests and capitalism. Workers belief in this can
be shaken by Labour governments, however not professional reformists who operate and see the
world very much in the framework of the state

** Who captures whom?

The Labour cabinet was very much captured by the state. They made clear to senior civil servants that
it would be business as usual

MacDonald's cabinet included almost no left wingers, however it did include tories and liberals

** Managing the system

The very first Labour cabinet set in motion the Emergency Powers Act, which gave authority for
the armed forces to do the work of strikers

The union bureaucracy supported the government in blocking strikes - they felt reluctantly compelled

** The true capiatlist party?

MacDonald announced at the opening of parliament that they would concentrate on rhte restoration of trade
rather than unemployment relief

Snowden, the chancellor, happily adopted an attitude of austerity.

** Wheatley makes his mark

John Wheatley managed to launch a house-building program, however he claimed (regretfully) that this wasn't a socialist
policy, and that he had merely co-ordinated capitalists

** The overall achievement

MacDonald was eager to prove to the ruling class that the LP was worthy. Tories and Liberals saw
little difference between LP policies and their own

** The Red bogey

In an effort to prove its anti-communist credentials, the government tried to prosecute a
communist editor for incitement to mutiny. It was a hopeless case and had to be dropped - MacDonald
then resigned due to this.

The Zinoviev letter was published - and rather than pointing out it was a bad forgery, MacDonald gave
it credibility

The LP lost seats in the next election (despite gaining votes) and became the main opposition

* 6. Revolution or reform: the left in the 1920s

Lenin believed that to acheive socialism, it was necessary to

- demonstrate that Labour's refomrism turns is against revolution
- break the LP's restraining influence
- win the majority of workers to a revolutionary alternative
  
** Home-grown attitudes to Labour  

The successor to the SDF was the BSP, it fully supprted the LP and
believed it could transform the pary to communism

The Socialist Labour Party was syndicalist - it wanted to destroy the LP

** Lenin's analysis

Lenin recognised the the LP was borgeouis, however it was necessary to cooperate
with it as it had the support of the larger body of workers

** The affiliation tactic

Lenin believed the Communists should leave the party, then apply for affiliation, while
being openly critical. He believed even rejection by RH and RM would be advantageous.

** Voting Labour

Lenin recommended voting Labour, if only to expose the bankruptcy of the PLP. He thought
disappointment would increase the chances of eventual overthrow

"I want to support Henderson in the same way as a rope supports a hanged man"

** The early Communist party
The 1921 conference rejected affiliation with the BCP

The BCP used a by-election in Caerphilly to allow a left-wing protest against the LP and build
its organization. The PLP was incensed, but this had the support of the workers. They won two seats
in parliament

** The inevitable pressures

Members of the BCP believed they couldn't achieve success without membership of the LP, this pulled them
towards reformism.

Tories openly defend the system, in practise the LP always defends it 

Similarly, the Mensheviks, who were far to the left of the LP, lined up with the most reactionary forces
against the Bolsheviks

** The Left Wing Movement

The LWM was formed by various left wing groups, with the intention of
building a left wing program in the LP

Its aim was to achieve conference resolutions - this meant little more than a left
sounding home for those disillusioned with the LP. It hindered workers discovering te true
nature of the LP.

** The theoretical flaw: Labour equals the trade unions

The theory underlying the LWM was that mass struggle would
drive unions leftwards, and convert the LP to revolutionary
politics, the latter following from identification of the LP with
the unions. Both were incorrect.

Union meetings could lead to revolutionary politics, albeit not via the
bureaucracy, as there is a common class bond. In LP meetings the common
bond is the election, and general reformist politics.

** From reformist mistakes to untra-leftism

The analysis of the CP, that the leadership would inevitable fall to the left,
was completely flawed.

Progress had always been made _despite_ the LP, in fact the influence of the LP
only grew after defeats

Rather than being pushed leftwards, in 1928 there was a communist witch-hunt, purging the LP.
This led to ultra-leftist calls to disaffiliate

** Trotsky's conrtibution

He correctly analysed the inadequacied in the LP, and correctly predicted that
Britain was on the eve of a class struggle - however he expected the CP to replace
the LP

** The ILP pays the price of reformist 'success'

The ILP had a majority of Labour MPs in the 20s, however it failed
to achieve real power. MacDonald had little respect for it.
The reason for its failure was that it always had to fail - it tried to
satisfy workers aspirations via capitalist institutions

** The Clydesiders

These were the most ourspoken MPs, getting ejected from parliament for their
lack of respect. However they had no intentions beyond 'shaking up' parliament - certainly
not smashing it

** 'Socialism in our time'

This was a policy devised by J A Hobson and the ILP. He looked for a minimum
wage - seeing the problems of capitalism as one of underconsumption.

At this point the empire started looking attractive to many in the LP as a source
of income.

** Poplarism

This was a well planned campaign to break council law in order to force
fairer distribution of council rates across London in 1921. Initially arrested, uproar led to
their release and accesion to their demands.

Four years later, with a complete lack of support by the new Labour government, Poplarism was defeated

** The balance sheet

The state had ceased to fear unrest. There was a change in tone in the 20s, from one of fear to amusement

* 7. General Strike and aftermath
** Background

Disillusioned by the first Labour government, the unions sought to keep the LP
out of their affairs

The LP was appaled by Red Friday, when the miners forced the government to subsidise their wages.

As the general strike approached, the LP claime to be on the miners side - however this support was
incompatible with capitalism, and so they sold out
** Solidarity, treachery and irrelevance

The PLP did _nothing_ to support the strike

The national executive doesn't appear to have even met during the strike
** Labour - the alibi for a sell-out

    The TUC leadership was terrified of the thought of confronting the state, and
    so used the LP as an excuse to keep out of the strike

    During 'normal' times, it might seem that the separation of politics and economics is sensible, however
    this is incorrect

    The communist party, wlthough tiny, was much more active
** The post-mortem

The PLP was delighted when the strike collapsed, as it entrenched their power at the
expense of the unions.

As in previous defeats, the workers looked to the LP to help them
** A horrific postscript

the LPs financial support for the miners was paltry to the point of cruelty

The Webbs suffered anguish over a donation of £10
** The fruits of defeat: the anti-communist witch hunt

The LP passed resolutions prohibiting people who had supported non-LP candidates from being delegates - this
meant communists. It proved unpopular and unworkable

The three main sections of the lP come into focus. The unions, which dominate conference, who are ignored by the PLP. Also
the constituency party, which can be much more left wing, however has less power than the unions.

Communists were used a a scapegoat when the 1924 election went badly

After the strike the LP began expelling local labour parties - despite some resistence, by 1928 the witch hunt was complete. At that
years conference the executive was the only body with the power to bring motions. A loyalty clause was introduced preventing even
associates of communists appearing on the same platform as LP members.

This had the effect of silencing the labour left

* 8 Reformists and the slump: the second Labour government

