#+DESCRIPTION: A summary of this book
#+TITLE: The Labour Party - A Marxist History
* Running themes
Reform or revolution

Separation of politics and economics 

Running the state more efficiently

The LP is a supporter of the state - even at the cost of votes

* Actors
** AH - Arthur Henderson

Leader of the party after MacDonald's removal due to his lack of enthusiasm for WWI
** BCP - British Communist Party

Founded in 1921 - supported Lenin and the Soviets
** LP - Labour Party
* 1. The birth of reformism
** The precursors: from Chartists to the Independent Labour Party
1. The LP has always separated politics from trade unionism, unlike the Chartists
2. After the failure of the 1842 general strike, the 1848 revolutions, and a subsequent economic boom,
   the working class grew more quiescent, to the extent they could start to be trusted with the vote in 1867
3. The first Labour MPs were elected in the 1870s, however these were working class people standing as Liberals
4. As Engels predicted, growth of US power caused the economic boom to falter later in the century
** From New Unionism to reformist politics
New general unions emerged in the late 1880s - these rejected the separation of politics and economics, older unions
were for more highly skilled workers in specific crafts. These unions recognised that strikes weren't enough, however
the support for revolution over reform was weak

The new unions were quickly weakened - capitalists fought back with lockdowns, the older unions obstructed, and the
Marxist SDF was 'incurably sectarian'. To protect their union machinery, new union leaders moved right

Bradford, which had suffered some of the greatest new union defeats, became the heart of the reformist movement.

The increase in miltancy, even although defeated, together with increasing economic problems, led to the breakdown of
Lib-Lab-ism laid the groundwork for the ILP
** The Independent Labour Party
Was founded in Bradford in 1893. It's aim was socialism, however explicitly via reformism and
electoralism

Initially it had no members, just affiliations

It was formed from the new union leadership, which although had moved to bureaucratism, were still
advanced in comparison with the old unions
** The myth of the Golden Age

The LP was never anything but reformist - despite later mythology presenting the party
as having fallen from grace
** The Dependent Labour Party

Reformism, having rejected Marxism, has no intellectual tradition. They
    'seek[] to channel working class aspirations in an ideological framework set by the system'

The ILP talked of smoothing over class conflict - they imagined that the rich would welcome socialism, as
they couldn't enjoy their riches while the working class was in misery.

Both Hardie and MacDonald turned to Labour only after rejection from the Liberals. Even so Hardie maintained
his support for them
** 'The worst enemies of social revolution'

The Fabians, in particular Beatrice and Sydney Webb, became the intellectual backbone
of the LP. Unfortunately they despised the WC. They supported eugenics, and opposed health
insurance.

Two influences were
    - Joseph Chamberlain's 'gospen of ransom' - i.e. get the WC just enough that they don't revolt
    - An ending of lassez faire - as Germany and the US became more powerful capitalists wanted
      the state to intervene

Their aims were to organize capitalist production at the state level. This would require no input from
the WC.

Lenin correctly said 'the LP is a thoroughly bourgeois party'
* 2. Out of the bowels of the TUC
** A background of defeat and passivity

By the late 1890s the old unions had recovered power. They were at first vehemently opposed to the
ILP, yet 5 years later they created the LP

Capitalists battered unions into submission, using the courts to establish the Taff-Vale decision, which made
strikers liable for lost profits. At the same time union bureacracy strengthened as membership increased, and
unions worked with employers via conciliation schemes.

Eventually the bureacracy realised they would struggle to justify their existence, and in their own interests
moved into politics

[For all its weaknesses, the ILP was born of an advanced LW movement - the LP was a step backward]
** The foundation conference creates a 'Labour Alliance'

The 1899 TUC called for a special congress to look into increaing the number of labour MPs
This congress created the LRC, which became the LP

The Marxist SDF wanted a completely separate party, recognizing class war and aiming for socialism
The right essentially wanted to continue Lib-Labism

Keir Hardie propsed a group having their own whips, with no marked political differences

The LP was created top-down, and initially the WC took little notice. They did poorly in the 1990 election,
electing just two MPs - uncluding Hardie. The ILP ran 10 candidates without victory.
** The political expression of the trade union bureaucracy

The LRC caused unions to begin to detach from the Liberals

Unions who affiliated did so cause they wanted to get into parliament. The coal and
cotton unions were last as due to geographical concentration they could ensure Lib-Lab MPs
were elected

Taff-Vale encouraged more unions to move into politics at the same time as they retreated from strike
action.

Although the LRC was created from the link between economics and politics, it sought to separate the two - while
maintaining some union attitudes. Just as unions don't really care about their members political beliefs as long
as they pay dues, the LP wanted workers votes regardless of their politics.
** The problem of false consciousness

The LP came about from a number of false beliefs

- that economics and politics can be separated
- they could reject class war and take a common-sense approach
- there is a community interest shared by all classes
** A technical division of labour

If the unions are once removed from class struggle, as they seek to bridge
the gap between workers and bosses, the LP is twice removed as it seeks the
votes of an electorate that is largely not union members.

Despite recommendations from union leaders, the LP did poorly even in heavily
unionised areas

It was for this reason that Bevin described the LP as being 'born out of the bowels of the TUC'
** Denying class in a class society

The LP is an uneasy combination of being very close to the unions, while seeking to appeal
to the nation.

The LRC initially had little or no policies of its own, instead generally supporting the Liberals.

Hardie wrote to several prominent Liberals to see if they would lead Labour - to no avail

MacDonald and Galdstone made a secret deal to not compete against each other
** Significance

The birth of Labour was a mixed blessing.
It was an advance on Lib-Labism, however it sought no political advance at the base.
As such it sacrificed the socialist ideals of the left wing as it looked to appeal to all classes.
** The impact of parliament

In 1906 29 MPs were sent to parliament.

At first they were struck with the lack of power - the inability to move the machinery of parliament.
They were also awestruck at meeting famous politicians, and being treated as equals by them
** Taming conference

The PLP was formed almost immediately. The 1907 conference gave MPs the freedom
to ignore conference - the first wording was too explicit, however there was no
change in meaning in the final version

They did manage to referse Taff-Vale, albeit relucantly and with the help of the
Liberals
** Poodles of Liberalism

By 1910 the number of MPs had grown to 42 - helped by the affiliation of the miners.

In 1910 they supported a minority Liberal government, and as in the 1906-10 parliament, they almost always
voted alongside them. MacDonald considered merging with the Liberals.

The support for the Liberals descended into farce when MacDonald scuttled his own motion, which was in effect
a motion of censure, when it seemed it might win.
** Left alternatives

The poor performance of the LP in these parliaments led to two reactions on the left
- mass militancy, i.e. a rejection of parliamentary methods
- the 'eternal' left - pushing the LP to accept more radical policies. 'eternal' because
  reformist policies always involve compromise with capitalism 

Hardie, MacDonald and others resigned en mass from the ILP at the next vote that went against
them

MacDonald saw parliament as more important than the plight of the WC. This was exactly opposite
to Lenin's view that parliamentary activity as the lowest form of the workers movement.
** The outside left


Syndicalists recognized the inadequacy of parliament

The LP emerged from Liberalism due to the the union unrest beginning in 1910.
Union membership doubled, there were several national strikes, and clashes with police.
** A brake on the movement

The LP wasn't consulted over any union action. It frequently spoke against
atrikes, describing parliamentary activity as the only was for socialism, and even as
being truly revolutionary.

Labour MPs proposed a bill making it illegal to strike without going through a 30 day
conciliation process. The punishments were draconian fines. The TUC caused it to be dropped

In 1913 the LP and unions reconciled in their opposition to the miners strike. They were both
at risk from syndicalism. However syndicalism had no policies besides strikes for better pay/conditions.
* 3. War and reconstruction: Labour adopts socialism
** An early casualty of the fighting

MacDonald was replaced by Henderson after expressing doubts about the war

In 1915 the LP joined Asquith's coalition

Internationalism was abandoned, and workers leaders supported the war
** Moralism and Labour politics

Hardie discussed the idea of a general strike to prevent war, this was
defeated by the unions, making a rare foray into politics.

Internationalism was viewsed as a 'nice to have' by reformists, but expendable

The ILP remained opposed to the war, even after the coalition.
** The meaning of the split

The ILP opposed the war, as did Hardie, MacDonald and Snowden. Unions succumbed to patriotic hysteria - this was
an occasion when crisis allowed the union bureaucracy to impose its wishes
** The diverse attitudes to war

Pro-war views within the LP were extreme. ILP opponents were hounded, a mahjority of
objectors who were tries were ILP members.

The LP, unlike the SPD in Germany, didn't break up. This was because the bulk of its
support came from the unions, and so could absorb the range of opinions the unions had.
** The limits of the ILP position

The position of LP opponents to the war was based on the inefficiency of war - they viewed it
as a failing of diplomacy. By contrast Lenin viewed war as an inevitable consequence of capitalist
and imperialist competition

** Clydeside: the legend and the reality

A myth has grown connecting the Clyde Workers Committee and the Labour MPs
elected in 1922

Although there were strikes by the Clyde engineers, these weren't anti-war

** The triumph of statism

As a result of the war, the state took over most production. In return for their suspending rules on
working conditions, the union leadership began to work directly with the government

The upper reaches of the labour movement were absorbed by the state

** Reconstructing the party

Revolutionaries had grown in number as the LP collaborated during the war - these held
no truck with the LP. Discontent grew, and the 1917 revolution concentrated the LP's mind.

** 'Uncle Arthur' - apostle of Labour's socialist conversion

Lloyd George sent Arthur Henderson to Russia to bolster Russian support for the war.
He was horrified by what he saw, in particulae the elevation of workers over directors.

Fearing the return of large numbers of radicalised troops, skilled with arms, he looked
to Sidney Webb to help safeguard against "Bolshevism" via a strong parliamentary LP.

** The 1918 constitution: a quest for the 'people's party'

Henderson and Webb looked to reorganise the party so that it would speak for the
nation rather than the WC. Given over 90% of the party was affiliated trade unions
it was difficult to present this as beyond class.

The 1918 constitution created local Labour parties and individual membership

The ILP was sidelined as punishment for its pacifism

** Socialism at last

Webb and Henderson created Clause Four as a conscious attempt to fend off
revolution

At previous conferences attempts to write socialism into the constitution generally failed,
as even socialists feared the LP would lose votes if they did

Contradictory motions were allowed, even at the same conference - so it was no more than lip service

** Labour's new social order

This document called for a legal minimum wage, welfare provision, and other social improvements.

This was a logical consequence of their belief that suffering was an _unnecessary_ consequence
of capitalism.

The wide state power exerted during the war led them to believe in this

** Social reconstruction and nationalisation

The LP sought to manage capitalism through widespread nationalisation

This wasn't a particularly left-wing POV at the time, and in no way suggested
workers would actually be in control

Nationalisation would cement the power the unions had gained during WWI

Finally, it suited the reformist aim of piecemeal takeover of industry, but as Marks said, this would be
".. a reformation within the boundaries set by the bourgeoisie"

* 4. Riding the post-war storm
** Did Labour prevent a British revolution?


In 1918 there were revolutionary outbreaks in Finland, Germany, Austria, Hungary and Bavaria
In all cases social democrats used 'socialism' as a fig-leaf for obsrtuction

AH openly claimed that the LP calmed revolutionary spirit - however this isn't correct, the
advanced workers largely ignored the LP
** The shifting centre of gravity

Although the LP did poorly in the 1918 election in terms of seats, and while it added
its voice to the anti-Bolshevik chorus, it was innefective in stopping the very great numbers of strikes
that occurred at this time.

The centre of power had shifted to the unions. The LP still played an importnat role as an alibi for
the unions
** Three disputes

In the Clydeside engineers strike for a 40 hour week the ILP tried to restrain the strikers

The miners and railwaymen struck for nationalisation, an 80% wage rise and 2 hour working day reduction.
Nationalisation was the problem - in a meeting with Lloyd George he told them they would win, but where they
prepared to take over the function of the state. They were not and opted for a commission of enquiry.

Similarly the leadership of the railwaymen brought their strike to an end in 9 days

Although the LP and ILP were largely irrelevant - for example their papers didn't even have industrial correspondents,
however their body of reformist ideas gave authority to the unions' brakes
** Direct action - threat or opportunity?

Although there was talk at this time of direct action, the counter-arguments won. After all,
what was the point of the LP if we don't acheive reform constitutionally?
** Labour's most daring hour

Lloyd George called for British troops to back the Poles against Russia - this one time the LP
supported calls for a general strike against this
** Black Friday - the transition to a governing party

At times betraying the revolutionary left can raise support for reformism - as there
is no other option

In 1921, an agreemet between railwaymen, transport workers and miners broke down when the colliery
owners demanded a 50% pay cut. Labour offered no support, and in fact criticised those who expected
unemployment benefits.

Despite this - union membership suffered, and as support for direct action eroded, it transferred to the LP
** The swing of the pendulum

As union membership plummeted, the vote for the LP in the 1922 election doubled on 1918.

A separation occured between the LP and the unions, with the latter losing or giving up their
authority and positions within the LP.

* 5. Proving Labour 'fit to govern': the 1924 administration

Reformists see no contadiction between WC interests and capitalism. Workers belief in this can
be shaken by Labour governments, however not professional reformists who operate and see the
world very much in the framework of the state

** Who captures whom?

The Labour cabinet was very much captured by the state. They made clear to senior civil servants that
it would be business as usual

MacDonald's cabinet included almost no left wingers, however it did include tories and liberals

** Managing the system

The very first Labour cabinet set in motion the Emergency Powers Act, which gave authority for
the armed forces to do the work of strikers

The union bureaucracy supported the government in blocking strikes - they felt reluctantly compelled

** The true capiatlist party?

MacDonald announced at the opening of parliament that they would concentrate on rhte restoration of trade
rather than unemployment relief

Snowden, the chancellor, happily adopted an attitude of austerity.

** Wheatley makes his mark

John Wheatley managed to launch a house-building program, however he claimed (regretfully) that this wasn't a socialist
policy, and that he had merely co-ordinated capitalists

** The overall achievement

MacDonald was eager to prove to the ruling class that the LP was worthy. Tories and Liberals saw
little difference between LP policies and their own

** The Red bogey

In an effort to prove its anti-communist credentials, the government tried to prosecute a
communist editor for incitement to mutiny. It was a hopeless case and had to be dropped - MacDonald
then resigned due to this.

The Zinoviev letter was published - and rather than pointing out it was a bad forgery, MacDonald gave
it credibility

The LP lost seats in the next election (despite gaining votes) and became the main opposition

* 6. Revolution or reform: the left in the 1920s

Lenin believed that to acheive socialism, it was necessary to

- demonstrate that Labour's refomrism turns is against revolution
- break the LP's restraining influence
- win the majority of workers to a revolutionary alternative
  
** Home-grown attitudes to Labour  

The successor to the SDF was the BSP, it fully supprted the LP and
believed it could transform the pary to communism

The Socialist Labour Party was syndicalist - it wanted to destroy the LP

** Lenin's analysis

Lenin recognised the the LP was borgeouis, however it was necessary to cooperate
with it as it had the support of the larger body of workers

** The affiliation tactic

Lenin believed the Communists should leave the party, then apply for affiliation, while
being openly critical. He believed even rejection by RH and RM would be advantageous.

** Voting Labour

Lenin recommended voting Labour, if only to expose the bankruptcy of the PLP. He thought
disappointment would increase the chances of eventual overthrow

"I want to support Henderson in the same way as a rope supports a hanged man"

** The early Communist party
The 1921 conference rejected affiliation with the BCP

The BCP used a by-election in Caerphilly to allow a left-wing protest against the LP and build
its organization. The PLP was incensed, but this had the support of the workers. They won two seats
in parliament

** The inevitable pressures

Members of the BCP believed they couldn't achieve success without membership of the LP, this pulled them
towards reformism.

Tories openly defend the system, in practise the LP always defends it 

Similarly, the Mensheviks, who were far to the left of the LP, lined up with the most reactionary forces
against the Bolsheviks

** The Left Wing Movement

The LWM was formed by various left wing groups, with the intention of
building a left wing program in the LP

Its aim was to achieve conference resolutions - this meant little more than a left
sounding home for those disillusioned with the LP. It hindered workers discovering te true
nature of the LP.

** The theoretical flaw: Labour equals the trade unions

The theory underlying the LWM was that mass struggle would
drive unions leftwards, and convert the LP to revolutionary
politics, the latter following from identification of the LP with
the unions. Both were incorrect.

Union meetings could lead to revolutionary politics, albeit not via the
bureaucracy, as there is a common class bond. In LP meetings the common
bond is the election, and general reformist politics.

** From reformist mistakes to untra-leftism

The analysis of the CP, that the leadership would inevitable fall to the left,
was completely flawed.

Progress had always been made _despite_ the LP, in fact the influence of the LP
only grew after defeats

Rather than being pushed leftwards, in 1928 there was a communist witch-hunt, purging the LP.
This led to ultra-leftist calls to disaffiliate

** Trotsky's conrtibution

He correctly analysed the inadequacied in the LP, and correctly predicted that
Britain was on the eve of a class struggle - however he expected the CP to replace
the LP

** The ILP pays the price of reformist 'success'

The ILP had a majority of Labour MPs in the 20s, however it failed
to achieve real power. MacDonald had little respect for it.
The reason for its failure was that it always had to fail - it tried to
satisfy workers aspirations via capitalist institutions

** The Clydesiders

These were the most ourspoken MPs, getting ejected from parliament for their
lack of respect. However they had no intentions beyond 'shaking up' parliament - certainly
not smashing it

** 'Socialism in our time'

This was a policy devised by J A Hobson and the ILP. He looked for a minimum
wage - seeing the problems of capitalism as one of underconsumption.

At this point the empire started looking attractive to many in the LP as a source
of income.

** Poplarism

This was a well planned campaign to break council law in order to force
fairer distribution of council rates across London in 1921. Initially arrested, uproar led to
their release and accesion to their demands.

Four years later, with a complete lack of support by the new Labour government, Poplarism was defeated

** The balance sheet

The state had ceased to fear unrest. There was a change in tone in the 20s, from one of fear to amusement

* 7. General Strike and aftermath
** Background

Disillusioned by the first Labour government, the unions sought to keep the LP
out of their affairs

The LP was appaled by Red Friday, when the miners forced the government to subsidise their wages.

As the general strike approached, the LP claime to be on the miners side - however this support was
incompatible with capitalism, and so they sold out
** Solidarity, treachery and irrelevance

The PLP did _nothing_ to support the strike

The national executive doesn't appear to have even met during the strike
** Labour - the alibi for a sell-out

    The TUC leadership was terrified of the thought of confronting the state, and
    so used the LP as an excuse to keep out of the strike

    During 'normal' times, it might seem that the separation of politics and economics is sensible, however
    this is incorrect

    The communist party, wlthough tiny, was much more active
** The post-mortem

The PLP was delighted when the strike collapsed, as it entrenched their power at the
expense of the unions.

As in previous defeats, the workers looked to the LP to help them
** A horrific postscript

the LPs financial support for the miners was paltry to the point of cruelty

The Webbs suffered anguish over a donation of £10
** The fruits of defeat: the anti-communist witch hunt

The LP passed resolutions prohibiting people who had supported non-LP candidates from being delegates - this
meant communists. It proved unpopular and unworkable

The three main sections of the lP come into focus. The unions, which dominate conference, who are ignored by the PLP. Also
the constituency party, which can be much more left wing, however has less power than the unions.

Communists were used a a scapegoat when the 1924 election went badly

After the strike the LP began expelling local labour parties - despite some resistence, by 1928 the witch hunt was complete. At that
years conference the executive was the only body with the power to bring motions. A loyalty clause was introduced preventing even
associates of communists appearing on the same platform as LP members.

This had the effect of silencing the labour left

* 8. Reformists and the slump: the second Labour government

Elected in 1929, the minority Labour government limped through the after effects of the Wall St crash
and the subsequent great depression. When MacDonald tried to get the cabinet to agree to a 10% cut in
unemployment benefits he achieved a majority but not a unanimous vote. He then formed a National Government.

In the 1931 election the Labour seats crumbled from 289 to 46

** The road to 1931

The LP had no concrete policies in their 1929 manifesto. They very much believed they were being elected to run
capitalism efficiently

They failed to repeal anti-union law brought in by Baldwin after the GS
They refused to bail out local authorities who had incurred debts supporting the miners
They forgot their election promise for a 7 hour day for the miners
They forgot their conference committment for an independent India at the earliest opportunity

As unemployment increased, the government refused to creat public works - they argued that unemployment was
necessary to work cheaply enough that private production would increase.

** Economic alternatives

Socialism was not one of the alternatives discussed, the LP claimed they had no mandate for that

Labour behaved like any capitalist government and opted for austerity - despite Keynsianism bing (a vague) part
of the manifesto

Mosley though Britain could isolate by using the empire for cheap raw materials, with state control of most everything at home.
This was nearly voted for in conference - Bevan was a supporter

Labour - while caught in the deadlights - were tolerated by the opposition as they thought it was easier for the LP to apply
austerity

The cabinet rejected the TUCs suggestion as to where savings could be made, instead
They asked the oppositions if a 10% dole cut would be ok...
who told them to ask the BOE...
who told them to check with the Federal Reserve...
who said they would speak to finanical leaders and get back to them

The reply was acceptance, as long as there was no hint of dissent in the cabinet. They failed to get a unanimous vote, so MacDonald
(possibly relieved) ended the government

** Aftermath

Riots ensued - the LPs only suggestion was that it would be better to vote Labour

The Invergordon mutiny - 12,000 seamen refused to obey orders after a 25% pay cut. The ensuing crisis
killed the gold standard

The flaws and contradictions in Labour's policy of reformism became apparent when capitalism was in crisis

Despite this the left was too weak to cause a revolutionary change in the LP 

* 9. From socialist dictatorship to National Unity: Labour in the 1930s

After severe electoral defeats the LP has tended to swing leftward - at
least in the short term

** Exit the ILP
Its 1931 conference voted to leave the LP - most MPs left to stay with the party

It then declined rapidly

** Cripps - A Jacobin in the ranks?

Cripps spoke of the necessity of recolutionary action, and of the futility of
change via constitutional means - however he always backed down when challenged

** Rise and fall of the Socialist League

Cripps was Chariman of the SL, which advocated revolutionary socialism,
and while the leadership was stunned by 'MacDonald's betrayal' it was
influential beyond its size

It won conference votes mandating immediate socialist legistlation upon the next Labour
government, and for nationalisation of all the banks

As the worst effects of the great depression eased, helped by the cushion of empire, the right
took back power and the SL was routed at the 1934 conference

** The Communist Party moulds the Labour left

The SL was weak as it had no links with the WC - if it were to break with the LP then
it would be isolated

The CP on the other hand had such roots, and union membership and the numbers of strikes began
to grow from 1934 - in practially all of these the CP was heavily involved

Jarrow was the only march supported by the LP and the TUC - largely because it was more a
charity march than political. On the other hand CP organised marches were met with police violence

The LP also opposed resistance to Mosley's fascists, even at Cable Street. The party 'both-sided' the
battle.

** Political dependence

The LP left was heavily dependent on the CP, however started to split after the purges, non-aggression pact, and
invasion of Poland

** Foreign policy

Labour was generally supportive of the state in the run-up to the war

Lansbury was replaced by Atlee when the former's pacifism became too much for the party

The Spanish Republicans were abandoned by the LP's policy of non-intervention

** The left alternative

The Socialist League opposed a war, and also denounce the League of Nations as capitalist

The Labour leadership refused a call by the CPGB for a united front against Nazism, both-sided the
Nazis and Communists, and claimed Nazism was a reactoin to Communism

The LP disaffiliated the Socialist League, which forced it to disband as LP membership was its raison d'etre.
It also banned any activity promoting a unified front with communists

** Sliding rowards the Popular Front

Calls for a popluar front to combat facism meant allying with capitalist forces. These
had no issue with Nazism itself, just its threat to the British Empire

Many on the left moved from supportinf a united front (of workers) to a popular front (of everyone)
very rapidly. However even this had no support from the LP leadership

Cripps was expelled from the party for his continued promotion of the popular front,
Bevan was also expelled for refusing to withdraw his support

** Disciplining the youth

The youth league was highly popular, vocal, and so disbanded by the leadership

* 10. The Labour Party during the Second World War

The war is portrayed as borgeouis democracy agains facism, however the allies
ruthlessly suppressed movements for colonial liberation - it was an imperialist war

In 1940 the LP joined a coalition with the Conservatives, with near total support within the party

Labour were given the home office and ministry of labour, but not the treasury

Bevin immediately implemented the Emergency Powers Act, essentially conscription for labour

Order 1305 banning strikes and lockouts was implemented in 1940 - the harsher Regulation 1AA which
threatened prison for strikes came in 1944. The TUC didn't resist any of these

** The government shows its true colours

The government refused to repeal the Trades Disputes Act, which was brought in after the General Strike.

The government also refused the independence of India

When the Nazis were defeated in Greece the British then attcked the resistance

** The Labour left's illusions in the coalition government

The Labour left convinced themselves that Churchill's desire to win the war was so single minded he
would permit socialist policies to achieve it

** In the Popular Front vice

A common theme was that the profit system impeded capitalism, and so nationalization would be
an inevitable policy

** The summit of reformism

WWII created full employment - union membership increased significantly, and strikes increased.
Workers were unhappy with profiteering

** The impact of class struggle on the left

There were tensions over to the extent the coalition should continue, however there was never a suggestion
that they withdraw from the government

** 'We are all Keynsians now'

Large numbers of politicians, both Labour and Conservative, saw the wasr as vindicating Keynes. There
was difference in emphasis (e.g. jobs vs inflation) and some resistance. Bevan asked what was the point
of the LP if they acccepted this

** The Beveridge Report

This was supported (at least in words) by Labour and some Conservatives. The LP would have moved for
very gradual implementation if it weren't for a massive back-bench rebellion

** Towards the first majority government

Soldiers had begun to mutiny, so there was no hope of using them to prevent major social change.

The mood within the LP had moved to fair wages, better housing, health, pensions etc were good for
capitalism

* 11. The Attlee government: zenith of reformism

** The apotheosis

Most everyone's memoirs speak in glowing terms of this administration, including Tony Benn

** Nationalisation

This met with little resistance. The industries in question, iron, steel, coal and the railways were all in need of massive
investment - which capitalists were reluctant to provide

Capitalists also needed the infrastructure these industries would provide

Nationalising the BOE was even supported as it fitted with most people being Keynsians

Workers were not given power. For example the NCB very much had the structure of a private company, and was even run by the
same managers

** Welfare

Beveridges welfare reforms weren't socialist, a section of capitalists viewed
them as bein necessary to improve the health of the workers whose labour they
consumed

It's in the light of this that Bevan's NHS should be viewed. He met with opposition from
the BMA, whose mouths he 'stuffed with gold'

The NHS _wasn't_ achieved as a result of class struggle, although it's form may be different
to what the Conservatives might have brought in. 

Labour attacked the NHS themselves before the end of their first government
n 

** The turning point: 1947, 'annus horrendus'

The winter of 1947 was terrible, this, combined with an increase of 2M unemployed
led to the first crisis. Reserves of dollars were depleted, the near 1M soldiers
abroad meant Britains reserves of dollars depleted, and austerity was the result

Austerity was inflicted by Cripps on the workers

** Wage restraint

In 1948 Attlee announced a wage freeze - this received reluctant support form the TUC

** The strike-breaking government

The military were used (or at least preparations were made) to break
many strikes - this was done enthusiastically by the cabinet, including Bevan

** Reforming zeal gives way to the consensus of 'Butskellism'

'Butskellism' was a term invented by the Economist to describe
the very similar policies of Rab Butler and Hugh Gaitskell

In 1946 the Conservatives had accepted state intervention to acheive full
employment

The low profitability of the already nationalised industries worked as propoganda
against nationalising steel and others

A split arose as to whether Labour should move right to capture the middle, or left
to differentiate themselves. In the end they did the former, and decided on a mixed
economy.

** A reactionary foreign and defense policy

Attlee 1937: "There is no agreement on foreign policy between a Labour
Opposition and a capitalist government"
Bevin 1945: "British foreign policy will not be altered in any way under the
Labour government"

Under the Labour government Britain was the most militarised non-communist
country in terms of spending (10%) and %age of military personnel

Attlee introduced conscription (National Service) of 18 months increased to 24
after the start of the Korean war.

With near unanimity Parliament voted to send troops in support of the US in Korea, and
also crushed uprisings in Grees, Malaya and Vietnam

** Indian independence: a shining exception?

Revolts in the Indian navy and massive civil unrest was what led to
Indian independence - in no sence socialism.

The independence agreement ensured British capital interests were untouched

** South Africa

British need for Uranium meant it happily overlooked the creation of Apartheid
with the claim that breaking relations would limit our power to influence SA

** Labour and the bomb

The decision of the Attlee government to begin a nuclear weapons program
was kept secret except for a very few cabinet ministers

** Remarkable complacency in the ranks

A period of docility, both on the part of Labour MPs, and the larger party.

This is a feature of Labour governments - in part because of the cabinet ministers
in the Executive, who are prevented from speaking about anything they have done as
privy councillors

** A feeble opposition: Keep Left

This was a short-lived manifesto, calling for european socialism and
a reduction in dependence on the US. It was killed by the Marshall Plan

** Tribune, loyal guard of the government

Pro: austerity, wage controls, US in Korea, imperialism in Africa, 2.5 year
conscription

** Conclusion

Attlee got away with being such a pro-capitalist due to the post-war world boom.

A conservative government would probably have brought in social reforms along the lines of Attlee,
perhaps not quite as much. However capitalists didn't fear a Labour government, and refused any
concessions they objected to. Attlee protected them from working-class power

* 12. 'Thirteen wasted years'

The predicted disaster and unemployment that would follow the election of
a Conservative government never occurred. However this was due still to the
ongong post-war boom

** The revisionists

A group of LP intellectuals, whose main figure was Anthony Crossland, who took
their name from Eduard Bernstein - who had arguse for the progressive benigness of
apitalism, in the late 19th century. Discredited by Rosa Luxwmburg, and the world wars, the
Russian revolution and the rise of the Nazis.

They similarly argued that capitalism was becoming less antagonistic, that the rise of the PMC
would reduce the profit incentive, and that nationalisation was now irrelevant.

** Bevanism

Bevan had no theory, and on economic policy didn't go against the party leadership
He did have objecton on foregin policy, bizarrely being _for_ NATO and _against_ SEATO

** The disintegration of Bevanism

Rather than risk expulsion, Bevan capitulated to the party right, becoming
shadow foreign secretary under Gaitskell.

He opposed nuclear disarmament

Also contented himself with an end to further nationalisation

** The attack on Clause Four

Gaitskell blamed calls for nationalisation for repeated election losses, and sought
to remove Clause Four. This was a step too far for the unions

** Labour and CND - a revolutionary road to socialism?

The 1960 conference approved unilateral disarmament - but this was a brief
punishment for Gaitskell over Clause Four. It was rejected the following year.

** The changing locus of reform

Labour were largely irrelevant during these years. Workers had power and exercised it.

* 13. The Wilson government 1964-69

** Revisionism's crowning victory: the 'scientific revolution'

The post-war boom was tapering in the early 60s. Growth while positive
was poor compared to other European countries.
Labour's manifesto attcked the tories on running capitalism badly. Other than
re-nationalisation of steel there were no socialist policies.
Wilson made his "white heat of scientific revolution" speech at the 1963 conference

** From the planning utopia to massive deflation

After consulting with industry (but nor workers) Labour came up with a plan to
increase manufactoruing investment by nearly 40% by 1970.

State planning in this case wasn't socialism, but yet again a more efficiently
run capitalism

Meanwhile the rate of profit continued to decline

** Deflation and devaluation

Wilson's fist budget, albeit with a 20% increas in old-age pensions, was
slightly deflationary. The BOE insisted on cuts to social security, however Wilson
threatened to float the pound and call another election.
The BOE blinked and borrowed $3B

Immediately after the 1966 election Wilson brought in the most deflationary budget yet. Wages were frozen,
public investment cut and indirect taxes increased. This was to avoid devaluation, however it instead
destroyed growth, increased unemployment (albeit to 2.6%) and devaluation occured in 1967 in any case.

In the later 60s Wilso pursued further deflationary measures, however profits continued to decline

** Incomes policy

To the delight of the Economist, Labour from 1964 supported an income policy,
capping wage rises. This was supported by the TUC

Their theory behind this was that it would permit profits to rise, and that these
were the fuel of capitalism

** Bashing the unions: In Place of Strife

To implement their incomes policy, Labour needed to inflict a heavy defeat ona striking union. They
chose the Seamen's Union, despite their managers being willing to settle.

Wilson accused the union of being infiltrated by communists - this was false and he knew it. The TWGU
gave no support and eventually the strike folded

** Workers do not knuckle under

Strikes increased during the late 60s. This activity came from below, and Labour propsed
restrictions in 1969 to limit such activity. This included a cooling off period, mandatory
ballots, and imposition of solutions

** Immigration and race

Upto Gaitskell Labour had opposed immigration restrictions, seeing it as a right
for Commonwealth citizens to settle in the UK. Wilson supported restrictions,
particularly after the Smethwick by-election, which he publicly condemned - however
the government saw immigration as a vote loser

The 1968 Immigration Act restricted rights of entry to those without a 'close connection'. This
included however those with a British grandparent, who were nearly all white.

** British foreign policy under Wilson

Wilson opposed any effective action against Rhodesia, supported the Vietnam war,
and was relaxed over arms to South Africa

He was happier using force in Aden and Cyprus

** Deep rifts between the Labour government and Labour Party

The 1966 government, having a comfortable majority, had the deepest divisions.
The PLP abstained or voted against the government on incomes policy and Vietnam,
however there were very few resignations - and others on the left were happy to
take the place of those who did resign.


conference frequently opposed government policy, to the extent it became routine, however
Wilson ran roughshod over this - threatening an election if necessary

The unions were critical yet did nothing

** Wilson and the Labour left

Criticism was varied - from Foot's hagiography, to Tribune's more open criticism of
income policy. Although the latter did absolutely nothing to support actual strikes against
this policy

** Alienation of workers from the Labour Party

The late 60s saw increased disillusionment in politicians. There was little difference
to be seen between the two parties, and Labour lost in 1970 with a poor turnout - despite
the lowering of the voting age to 18

** The end of the reformist era

After 1965, Vietnam led to inflation. The associated balance of payments crisis
encouraged attacks on wages

Until this point Keynsianism had suggested that what was good for workers was good
for the economy in general. Now high wages were the enemy.

Attlee reform had clearly not been a springboard to further progress.

Attlee's nationalisation of the worst performing industries allowed the press to portray
state run industry as inherently poor

* 14. The Labour Party under the Heath government
** The industrial scene

The Heath government introduced anti-union legislation along the lines that Labour
had intended. This involved union registration - which all major unions refused to do.

Massive strikes and demonstrations in Scotland prevented the closure of shipworks, similarly the
government was forced to change the law to free improsoned strikers.

The coal miners strikes eventually brought down the government - which had issued a state
of emergency 5 times.

Labour meanwhile were silent
** Who led the massive industrial struggles?

Initially the CP led the vanguard of shop stewards, however its decision to achieve power
through both communist and left-wing Labour MPs inhibited it, and left it useless

In its place came the International Socialists, a precursor to the SWP
** The echo of the battle: Labour's customary leftward swing

A combination of industrial militancy, the awfulness of the Wilson government, meant
a sharp move leftwards. Even Dennis Healey got in on the act.

Conference voted for massively increased nationalisation, in some cases without compensation.
Also unilateral disarmament, and the removal of US bases.

It also resolved that conference should be sovereign, and deplored that Labour in government
ignored their resolutions
** The birth of the Alternative Economic Strategy

This was adopted by the ocnference of 1973. It decided that there should be state planning,
while businesses were still in private hands.

It would bring in capital controls, leave the EEC, prevent Sterling from being freely convertible,
put its own directors on the boards of multinationals...

Again.. while businesses were still in private hands and motivated by profit.

Its ideas were essentially nationalist Keynsianism
** The Social Contract

This extended the AES to include price and rent controls, and further social benefits

It also repealed anti-union laws
** Parasite lost

Despite the radical program, the link between Labour and radical left-wing politics had
been broken. This was due to the previous Wilson government, and the party's complete
lack of support for industrial action.

It won the election on a reduced vote, mainly due to the Liberals doubling their share to nearly 20%

* 15. The Labour government of 1974-79

The Attlee government had subdued militancy with reforms. The 74-79 didn't even
offer that

** The bankruptcy of Keynsianism

The 70s broke the theory of the Philips curve, which predicted that employment above 3.5%
would be deflationary. Inflation was higher than 10% at the time.

The inflation was in fact caused by the enormous amount of spending on the Vietnam war, huge bail-outs
for too-big-to-fail private corporations, and the power of monopolies to offset declining profits with price
rises.

The first monetarists were in fact Dennis Healey and Geoffrey Howe - not Thatcher.

Wilson declared the inflation had to be defeated before they could acheive full employment

** Little freedom of manouvre for Labour government

International capital flows meant that 'Keynsianism in one country' was not possible.
The British fraction of world trade had decreased by two thirds since 1900. Although
there was a considerable period of post war growth, it was less than comparable countries.
There was a lack of capital investment - about one third of Germany's

Healey made it clear to the CBI that he had no intention of making them pay

** Promises of radical measures ditched

If Labour had tried to implement its manifesto, it would almost certainly have been defeated
by international capitalism, the Trasury and the BOE. The CBI had a list of (illegal) measures
it planned to take - including non-payment of taxes.

Labour brought bankrupt companies into the NEB - fixed them and handed them back to the private sector.

Meanwhile public spending was drastically cut by 10% in real terms between 1976-8

** Incomes policy once more

Labour talked of a grand union of Government, Industry and Trade Unions. However it had no
control over the IMF, CBI or capital in general. It could however try to exert control on the
workers.

Between 1975-78 it applied wage controls, significantly reducing wages in real terms. The unions
supported this for the first couple of years. Year 4 was the winter of discontent.

** Blunting workers' militancy

A commission formed in 68 by Wilson advised on how to handle unions. It recommended making
shop stewards full time, so as to separate them from the workers and tighten their links with
union bureaucracy.

This, together with union participation on boards meant that they became the managements' police

They even encouraged scabbing when workers acted against the deals that had been agreed above their heads.

The miners rejected a proposed productivity scheme with the NCB - two times, despite this being against their
constitution. Eventually Joe Gormley forced the regions to negotiate their own deals with the NCB. This
weakened the miners considerably

** A Chamber of Horrors: the Labour government's economic record

Unemployment of nearly 1M in 1971 had forced Heath into a raft of reflationary measures.
Under Callahan unemployment reached 1.6M, yet it felt no such pressure as it feared unions and
workers less

** The National Front: ugly child of government policies

The worst economic results cince the war led to increased support for the NF. Labour reacted by supporting
their policies, and speaking out against immigration.

The battle of Lewisham was denounced by the LP - yet led to the formation of the Anti-Nazi League and Rock against Racism.
This - together with active campaigning led to a huge decreas in the NF vote

** The Labour government and the bomb

Despite the vote in conference for unilateral disarmament, Wilson and later
Callahan spent £1B on Polaris

** Labour and Northern Ireland

Labour and the Tories had essentially the same policies on NI. Michael Foot was resoundingly
cheered when he celebrated Thatcher's resistance of the hunger strikers.

Callaghan supported the aemy after Bloody Sunday

In 1977 they went into a parliamentary alliance with the unionists, paying with 6 extra parliamentary seats

** Deep divisions between government and party

Conference voted against the government many times. Wilson's strategy was to simply
ignore it. Despite ther being a policy that conference motions with more the 2/3rds majority
had to be pu on the manifesto, Wilson refused to put the abolition of the house of Lords there.

The numbers of divisions with dissenting votes in this parliament was more than all there had been since the war

Even the cabinet had little power - only learning of budgets the day before they were announced. Callaghan had no idea
of the budget's contents when he became leader.

In turn the chancellor had little power compared to the BOE and Treasury

** The contortions of Tony Benn

Benn only shifted left during the Heath government. He torn between wanting to be the
best-known left winger, and staying in the cabinet. When these clashed he chose the latter.

He was happy to impor Uranium fro South African run Namibia, aplogised for censuring the Royal Navy for
doing joint exercises with South Africa. Supported the NUM impositions of regional incentives, despite a majority
of members being against it

** The denouement

After the winter of discontent the party lost the next election badly

* 16. Labour under Thatcher
** Downturn on the industrial front

Rising unemployment, together with a fragmented workforce, plus increased union
bureacracy meant Thatcher met little effective resistance.

The TUC and the LP gave no support to strikers.

The miners had been split by regional bargaining enforced by Labour
** Political upturn: Bennism

The left's focus was wasted on constitutional issues. Mandatory reselection was brought in,
and members would now be included in the election of a leader, not just the PLP. However
power resided in the NEC, and this was mostly appointed by the unions.

After the 81 conference the GoF left to form the SDP. Labour's support halved in the polls,
and they barely came second in the 1984 election.

Benn vastly overestimated his support - which was largely in the leadership of some unions
with large block votes
** Labour and the Thatcherite consensus

Thatcher's privatisaion planned to sell so much of state owned enterprises
that Labour could never buy them back - especially as they were far from a post-war
boom ecenomy.

The party was divided on the subject. While there were some calls for renationalisation,
some watered this down to workers owning a share. Share ownership itself was spoken
of approvingly
** Partnership with private industry

Hattersley went out of his way to reassure the rich he wouldn't tax them.
He also criticised past levels of spending. He further said there was no point
in implementing capital controls as capitalists would curcumvent them.

Kinnock spoke of the importance of keeping inflation low, and how we are all in this
together - no more 'them and us'

The LP was happy to maintain Thatcher's anti-union laws

On unemployment the goal of the 9187 election was to reduce it from 4M to 3M over two years.
** Bennism in retreat and the witch-hunt against Militant

Foot delivered a jingoistic speech in favour of the Falklands War - Benn came close

The part planned to set up a register of organisations - intending to witch-hunt Militant

At the time the Labour left was weak, Militant far weaker than the CP had been when they were
expelled in the 1920s

Militant had some support in the unions, but outside of Liverpool very little amongst the membership
** The 'dream ticket': Neil Kinnock becomes leader

Kinnock began on the left of the party, voting against the Labour government far more
times than Benn. Yet had moved right by the time he was elected, offering no support
for the NUM and houding out Militant
** The collapse of 'municipal socialism'

Labour councils were elected on a 'No cuts, no rent rises, no rate rises' manifesto.
In fact they did all three

Despite support for resistence to cuts in government spending from the 1983 conference,
Kinnock said it was better to stay in order to protect services. A dented shield being better
than no shield. It turned out the dented shield protected capitalism from the
workers

Councillors were unwilling to risk imprisonment. Unlike at Poplar in the 20s, there were no
strong ties between councillors and a wider movement they could draw on for support
** Feminism: a broken reed

Feminism in the 80s, after a series of industial defeats, was individualist.
Whereas the 70s had brought the equal pay act, abortion and free contraception
** New realism: exploiting political advantage from electoral defeats

Why had Labour lost support

The standard analysis at the time was that workers had moved to white-collar jobs.
However the greates such shift occurred in the 1960s, when Labour had high support.

Another explanation was the increase in shareholders - however this was grossly
overestimated

More likely was the memory that Labour never actually supported working class actions
** Workers' organisations intact

Labour was beginning to see unions as less relevant. However union
membership declined very little, despite the increase in unemployment, and
those in work were able to protect their wages through industrial action
** Did Thatcher win the ideological battle?

Nope - according to British Social Attitudes the general public
saw clearly the injustices prevailing. However they simultaneaously
believed that we would all be better off if businesses mad higher profits, wile
maintaining that the bulk of these profits would go to shareholders and managers.

They further had quite an authoritarian streak
** So why did Thatcher win three elections in a row?

Kinnock made it easier for Thatcher to escape highly unpopular decisions - such as the
bombing of Libya

On South Africa it was easy for Thatcher to dig up quotes by the LP against sanctions

Lack of faith in the LP due to its not supporting workers. Very few people identified
with a political party in the 80S
** The Labour Party in 1987

Kinnock put the blame on the hard left, blacks and gays. He opposed the creation
of Black sections

Kinnock and Brian Gould wanted to leapfrog Thatcher, gy advocating 'shares for all'

He introduced 'one-member-on-vote' for the election of parliamentary candidates. This
was claimed to be more democratic, however he was aware of the gulf between active and passive members
and knew the latter would be more susceptible to right wing media

He spoke in glowing terms of Reagan's foreign policy
** Full circle

Reforms are less dependent on which party is in power, than in the strength
of the working class. The Tories expanded the welfare state in the 1950s. Labour
introduced monetarism in the 1970s

If Labour were in government, it offers nothing distinctive to the Tories in the face
of international capitalism

The party began as an imitation of the Liberals, and under Kinnock was an even paler imitation
of the Tories

* 17. New Labour
** The fall of Thatcher and the poll tax

Despite its huge unpopularity, Labour opposed any resistance to the tax. Labour councils
prosecuted non-payers with enthusiasm. They withdrew the whip from councillors who
said they wouldn't prosecute.

Cherie Blair demanded a penniless non-payer be returned to jail

The poll tax 'riots' were condemned by labour, with calls for stiff sentences.

When the poll-tax was defeated, Blunkett claimed it as a victory of theirs.
** Labour's Gulf war syndrome

When the war begain in 1991, there were no calls for a parliamentary debate. Kinnock
fawningly sided with John Major

Before the war began Labour were 15 pts ahead, largely due to the poll tax. After the war they were 5 pts behind
** The 1992 election

Labour - bizarrely - chose to focus on policies of little interest to the electorate, such as PR,
instead of the NHS. It was also a presidential style election, focussing very much on Kinnock

After their defeat the blame was put on their policies of increasing taxation for the rich - regardless
of the evidence
** The mines tragedy

Labour offered no support to striking miners when further pit closures were announced.

Unions resisted strike calls in general due to the hope of a forthcoming Labour government
** One Member One Vote - Weakening the union link

Although for much of its history the membership had been to the left of the unions, in
the 90s, after electoral defeats, its membership drew right wing conclusions

The unions were blamed for the loss, however the scored much lower than Kinnock himself
in peoples reasons for not voting Labour

The unions, needing Labour support in the event of a Labour victory, allowed the rule change to
go ahead.
** New Labour's new members

The advantage for Labour of OMOV was the absence of informed debate. Instead members
could do postal votes from their own homes.
However even the pasive membership was to the left of the leadership. To counter this
left wing groups were purged in the early 90s, in particular young labour.

The membership consisted more of well meaning professionals than working class
** The Labour left's manic depression

The left suffered due to the changes in membership and voting rules. Benn was dropped from the NEC,
power was centralised, and Blair beame the most right-wing leader Labour had ever had.
Claire short went from dire warnings about the modernisers to full throated support of Blair
** The evolution of Labour policies

from 87 to 92 public opinion shifted left, however Labour policy didn't

They moved from unitlateral disarmament to multi-lateral to re-armament

Created non-unionised foundation schools, despite charter schools being very unpoular

"Tough on crime, tough on the causes of crime" - the latter didn't mean unemployment or poverty,
rather a lack of obedience

The Tories' Criminal Justice Bill was designed to be so extreme that Labour would oppose it while they were trying to
loog tough on crime -in the end they made minor quibbles and abstained

Labour looked to retain much of the Tories NHS reforms. Patricia Hewitt recommended ending universal helth care free at the point
of delivery

Harriet Harman reassured the CBI that 18-24 year olds would receive a much lower wage

Brown - "Labour is not against wealth, nor will we seek to penalise it"
Blair - "If someone goes ont o be wealthy, good luck to them"

Ken Clarke remarked on how little crticism he received (as chancellor)

Brown - "Labour will be tougher on the causes of inflation than the Conservatives"

Blair had no wish to extend union law beyond those granted by the EU social charter
** Tony Blair and Labour

Thatcher was a fan of Blair, and vice-versa

He thought the party had moved beyond left and right

He told the unions they would no longer have an arm-lock on policy [when did they?]
** Back to the pre-1918 era?

Blair claimed that Socialism was not about class or trade unions

Dropping clause 4 fitted with Thatcher's desire to see two political parties
committed to capitalism

Many Labour members supported the clause 4 changes as they though Blair was the only
chance of getting a Labour government

The balancing act that Labour had performed for capitalism became harder, as reformist demands - such
as a job, healthcare, and basic services clashed with the desires of capital to increase exploitation
** Prospects for a Blair government

Labour equivalents in Australia, New Zealand and Spain all decreased wages,
and increased inequality and unemployment

Pre 1997, Blair described the party as being free from particular policy prescriptions

Blair spoke of how we needed 'entrepeneurs and people who can go out and make a lot of money'

However for workers '... insecurity at work a permanent feature of life'
However Mandelson suggested
    abolition of universal child benefit
    workfare programs for the unemployed and single mothers
    private pensions
    schools free of LEA control

** Stakeholding

Taken from Will Hutton - this amounted to a modernised Keynsianism, but meant even less
when Blair said it. He assured the CBI it wouldn't strengthen workers rights

Blair announced the policy in Singapore - who's happy facism he seemed to like

Stakeholding was based on a cohesive society, which reeked ot one nation toryism. 

* 18. New Labour in government
** How new was New Labour?

While Blair was elected 3 times, at the end of his 13 years the U.K. was one of the most unequal
countries, with lowest social mobility

Before Blair, arguments (at least publicly) were about the speed of reform.
Under Blair that was no longer the case - he didn't want to improve conditions for the WC
** The most popular government ever!

Not really... The %age vote was less than even in losing elections in the 50s and 60s.
Turnout was also poor

The 2001 election had an even worse turnout (< 60%) and the 2005 only slightly more.
The 2005 election gave Labour a clear majority with the smallest %age of the vote in history (35%)

Gordon Brown lost in 2010 - the history written by TB suggested the problem was not sticking to New Labour policies,
although there was precious little difference between them

Brown described the government as always being a "pro-business, pro-enterprise and pro-competition government"
** New Labour and class

Blair: "Thatcher had done the right thing in liberating enterprise and industry"
"we had to divest power away from the dominant interest groups, unions and associations"

He thought a minimum wage of £3.50 crazily high

He told the Sun that the UK's labour laws were the most restrictive in Europe - as a good thing

He hoped to break the link with the unions, despite strikes in the 90s being at record lows

Union leaders did little to challenge this

The bloc vote at conference was reduced, and the ability to raise motions removed - as it was from CLPs

The 1998 conference was mostly attended by lobbyists, business representatives and journalists

All but one of the £1M plus donors were given peerages

As chancellor, Brown cut corporation tax to its lowest ever level, and commited to reduce
public spending

He considered the poor as being too lazy to work - and reduced unemployment by moving people into
low paid jobs
** Public spending

There was increased NHS spending, raising the UK to the OECD average, however there was increased privatisation.
The PMC took over hospitals, and PFI turned out to be eye-wateringly expensive - to the extent that
Cameron abandoned it
** The Home Office

New Labour re-created the undeserving poor. Spoke against universal benefits, and created
many more crimes

On immigration, due to fear of it being an issue they could lose votes on, they move rightwards.
This gave credibility to the BNP whose vot share increased significantly. They made it near
impossible for refugees to come to the UK, thus forcing them to try illegally.
** War at home and abroad...

Blair liked war. With Kosovo, Sierra Leone, Afghanistan and Iraq he killed more UK soldiers than
anyone since Churchill - and of course 1M Iraqis

Blair encouraged Bush and Clinton towords military action - rather than diplomatic 

Brown said it was time to stop apologizing for the Empire, and we should celebrate much of it

The trigger for Blair's resignation was his failure to condemn Israel's killing of 1300 Lebanese, as the
region had many injustices, of which the palestinians was only one
** The 'no more boom and bust' prime minister

And the 2008 happened. Brown portrayed himself as an innocent victim, and his handing over public cash to
the banks as 'saving the world' - although it probably was accurate that he saved capitalism
** Inside and outside Labour

Labour was viewed by its members as centralized and controlling - couse it was

Livingstone was replaced by Frank Dobson as the Labour candidate for London Mayor, however
Ken still ran and won easily. Dobson came third

The PLP rebellion against the second Iraq war was much bigger than the first - because of the huge
deomonstration
** Conclusion

Rosa Luxemburg said that those who seek legislative reform aren't seeking a different path to the same
goal, but a different goal

* 19. From Milliband to Corbyn

Ed won cause he had more union support, being seen as more distant from Blair compared
to David

