#+TITLE: The Labour Party - A Marxist History
#+DESCRIPTION: A summary of this book
* Running themes
- Separation of politics and economics 
- Reform or revolution
- Running the state more efficiently
* 1. The birth of reformism
** The precursors: from Chartists to the Independent Labour Party
1. The LP has always separated politics from trade unionism, unlike the Chartists
2. After the failure of the 1842 general strike, the 1848 revolutions, and a subsequent economic boom,
   the working class grew more quiescent, to the extent they could start to be trusted with the vote in 1867
3. The first Labour MPs were elected in the 1870s, however these were working class people standing as Liberals
4. As Engels predicted, growth of US power caused the economic boom to falter later in the century
** From New Unionism to reformist politics
New general unions emerged in the late 1880s - these rejected the separation of politics and economics, older unions
were for more highly skilled workers in specific crafts. These unions recognised that strikes weren't enough, however
the support for revolution over reform was weak

The new unions were quickly weakened - capitalists fought back with lockdowns, the older unions obstructed, and the
Marxist SDF was 'incurably sectarian'. To protect their union machinery, new union leaders moved right

Bradford, which had suffered some of the greatest new union defeats, became the heart of the reformist movement.

The increase in miltancy, even although defeated, together with increasing economic problems, led to the breakdown of
Lib-Lab-ism laid the groundwork for the ILP
** The Independent Labour Party
Was founded in Bradford in 1893. It's aim was socialism, however explicitly via reformism and
electoralism

Initially it had no members, just affiliations

It was formed from the new union leadership, which although had moved to bureaucratism, were still
advanced in comparison with the old unions
** The myth of the Golden Age

The LP was never anything but reformist - despite later mythology presenting the party
as having fallen from grace
** The Dependent Labour Party

Reformism, having rejected Marxism, has no intellectual tradition. They
    'seek[] to channel working class aspirations in an ideological framework set by the system'

The ILP talked of smoothing over class conflict - they imagined that the rich would welcome socialism, as
they couldn't enjoy their riches while the working class was in misery.

Both Hardie and MacDonald turned to Labour only after rejection from the Liberals. Even so Hardie maintained
his support for them
** 'The worst enemies of social revolution'

The Fabians, in particular Beatrice and Sydney Webb, became the intellectual backbone
of the LP. Unfortunately they despised the WC. They supported eugenics, and opposed health
insurance.

Two influences were
    - Joseph Chamberlain's 'gospen of ransom' - i.e. get the WC just enough that they don't revolt
    - An ending of lassez faire - as Germany and the US became more powerful capitalists wanted
      the state to intervene

Their aims were to organize capitalist production at the state level. This would require no input from
the WC.

Lenin correctly said 'the LP is a thoroughly bourgeois party'
* 2. Out of the bowels of the TUC
** A background of defeat and passivity

By the late 1890s the old unions had recovered power. They were at first vehemently opposed to the
ILP, yet 5 years later they created the LP

Capitalists battered unions into submission, using the courts to establish the Taff-Vale decision, which made
strikers liable for lost profits. At the same time union bureacracy strengthened as membership increased, and
unions worked with employers via conciliation schemes.

Eventually the bureacracy realised they would struggle to justify their existence, and in their own interests
moved into politics

[For all its weaknesses, the ILP was born of an advanced LW movement - the LP was a step backward]
** The foundation conference creates a 'Labour Alliance'

The 1899 TUC called for a special congress to look into increaing the number of labour MPs
This congress created the LRC, which became the LP

The Marxist SDF wanted a completely separate party, recognizing class war and aiming for socialism
The right essentially wanted to continue Lib-Labism

Keir Hardie propsed a group having their own whips, with no marked political differences

The LP was created top-down, and initially the WC took little notice. They did poorly in the 1990 election,
electing just two MPs - uncluding Hardie. The ILP ran 10 candidates without victory.
** The political expression of the trade union bureaucracy

The LRC caused unions to begin to detach from the Liberals

Unions who affiliated did so cause they wanted to get into parliament. The coal and
cotton unions were last as due to geographical concentration they could ensure Lib-Lab MPs
were elected

Taff-Vale encouraged more unions to move into politics at the same time as they retreated from strike
action.

Although the LRC was created from the link between economics and politics, it sought to separate the two - while
maintaining some union attitudes. Just as unions don't really care about their members political beliefs as long
as they pay dues, the LP wanted workers votes regardless of their politics.
** The problem of false consciousness

The LP came about from a number of false beliefs

- that economics and politics can be separated
- they could reject class war and take a common-sense approach
- there is a community interest shared by all classes
** A technical division of labour

If the unions are once removed from class struggle, as they seek to bridge
the gap between workers and bosses, the LP is twice removed as it seeks the
votes of an electorate that is largely not union members.

Despite recommendations from union leaders, the LP did poorly even in heavily
unionised areas

It was for this reason that Bevin described the LP as being 'born out of the bowels of the TUC'
** Denying class in a class society

The LP is an uneasy combination of being very close to the unions, while seeking to appeal
to the nation.

The LRC initially had little or no policies of its own, instead generally supporting the Liberals.

Hardie wrote to several prominent Liberals to see if they would lead Labour - to no avail

MacDonald and Galdstone made a secret deal to not compete against each other
