#+TITLE: The Labour Party - A Marxist History
#+DESCRIPTION: A summary of this book
* Running themes
- Separation of politics and economics 
- Reform or revolution
- Running the state more efficiently
* 1. The birth of reformism
** The precursors: from Chartists to the Independent Labour Party
1. The LP has always separated politics from trade unionism, unlike the Chartists
2. After the failure of the 1842 general strike, the 1848 revolutions, and a subsequent economic boom,
   the working class grew more quiescent, to the extent they could start to be trusted with the vote in 1867
3. The first Labour MPs were elected in the 1870s, however these were working class people standing as Liberals
4. As Engels predicted, growth of US power caused the economic boom to falter later in the century
** From New Unionism to reformist politics
New general unions emerged in the late 1880s - these rejected the separation of politics and economics, older unions
were for more highly skilled workers in specific crafts. These unions recognised that strikes weren't enough, however
the support for revolution over reform was weak

The new unions were quickly weakened - capitalists fought back with lockdowns, the older unions obstructed, and the
Marxist SDF was 'incurably sectarian'. To protect their union machinery, new union leaders moved right

Bradford, which had suffered some of the greatest new union defeats, became the heart of the reformist movement.

The increase in miltancy, even although defeated, together with increasing economic problems, led to the breakdown of
Lib-Lab-ism laid the groundwork for the ILP
** The Independent Labour Party
Was founded in Bradford in 1893. It's aim was socialism, however explicitly via reformism and
electoralism

Initially it had no members, just affiliations

It was formed from the new union leadership, which although had moved to bureaucratism, were still
advanced in comparison with the old unions
** The myth of the Golden Age

The LP was never anything but reformist - despite later mythology presenting the party
as having fallen from grace
** The Dependent Labour Party

Reformism, having rejected Marxism, has no intellectual tradition. They
    'seek[] to channel working class aspirations in an ideological framework set by the system'

The ILP talked of smoothing over class conflict - they imagined that the rich would welcome socialism, as
they couldn't enjoy their riches while the working class was in misery.

Both Hardie and MacDonald turned to Labour only after rejection from the Liberals. Even so Hardie maintained
his support for them
** 'The worst enemies of social revolution'

The Fabians, in particular Beatrice and Sydney Webb, became the intellectual backbone
of the LP. Unfortunately they despised the WC. They supported eugenics, and opposed health
insurance.

Two influences were
    - Joseph Chamberlain's 'gospen of ransom' - i.e. get the WC just enough that they don't revolt
    - An ending of lassez faire - as Germany and the US became more powerful capitalists wanted
      the state to intervene

Their aims were to organize capitalist production at the state level. This would require no input from
the WC.

Lenin correctly said 'the LP is a thoroughly bourgeois party'
* 2. Out of the bowels of the TUC
** A background of defeat and passivity

By the late 1890s the old unions had recovered power. They were at first vehemently opposed to the
ILP, yet 5 years later they created the LP

Capitalists battered unions into submission, using the courts to establish the Taff-Vale decision, which made
strikers liable for lost profits. At the same time union bureacracy strengthened as membership increased, and
unions worked with employers via conciliation schemes.

Eventually the bureacracy realised they would struggle to justify their existence, and in their own interests
moved into politics

[For all its weaknesses, the ILP was born of an advanced LW movement - the LP was a step backward]
** The foundation conference creates a 'Labour Alliance'

The 1899 TUC called for a special congress to look into increaing the number of labour MPs
This congress created the LRC, which became the LP

The Marxist SDF wanted a completely separate party, recognizing class war and aiming for socialism
The right essentially wanted to continue Lib-Labism

Keir Hardie propsed a group having their own whips, with no marked political differences

The LP was created top-down, and initially the WC took little notice. They did poorly in the 1990 election,
electing just two MPs - uncluding Hardie. The ILP ran 10 candidates without victory.
** The political expression of the trade union bureaucracy

The LRC caused unions to begin to detach from the Liberals

Unions who affiliated did so cause they wanted to get into parliament. The coal and
cotton unions were last as due to geographical concentration they could ensure Lib-Lab MPs
were elected

Taff-Vale encouraged more unions to move into politics at the same time as they retreated from strike
action.

Although the LRC was created from the link between economics and politics, it sought to separate the two - while
maintaining some union attitudes. Just as unions don't really care about their members political beliefs as long
as they pay dues, the LP wanted workers votes regardless of their politics.
** The problem of false consciousness

The LP came about from a number of false beliefs

- that economics and politics can be separated
- they could reject class war and take a common-sense approach
- there is a community interest shared by all classes
** A technical division of labour

If the unions are once removed from class struggle, as they seek to bridge
the gap between workers and bosses, the LP is twice removed as it seeks the
votes of an electorate that is largely not union members.

Despite recommendations from union leaders, the LP did poorly even in heavily
unionised areas

It was for this reason that Bevin described the LP as being 'born out of the bowels of the TUC'
** Denying class in a class society

The LP is an uneasy combination of being very close to the unions, while seeking to appeal
to the nation.

The LRC initially had little or no policies of its own, instead generally supporting the Liberals.

Hardie wrote to several prominent Liberals to see if they would lead Labour - to no avail

MacDonald and Galdstone made a secret deal to not compete against each other
** Significance

The birth of Labour was a mixed blessing.
It was an advance on Lib-Labism, however it sought no political advance at the base.
As such it sacrificed the socialist ideals of the left wing as it looked to appeal to all classes.
** The impact of parliament

In 1906 29 MPs were sent to parliament.

At first they were struck with the lack of power - the inability to move the machinery of parliament.
They were also awestruck at meeting famous politicians, and being treated as equals by them
** Taming conference

The PLP was formed almost immediately. The 1907 conference gave MPs the freedom
to ignore conference - the first wording was too explicit, however there was no
change in meaning in the final version

They did manage to referse Taff-Vale, albeit relucantly and with the help of the
Liberals
** Poodles of Liberalism

By 1910 the number of MPs had grown to 42 - helped by the affiliation of the miners.

In 1910 they supported a minority Liberal government, and as in the 1906-10 parliament, they almost always
voted alongside them. MacDonald considered merging with the Liberals.

The support for the Liberals descended into farce when MacDonald scuttled his own motion, which was in effect
a motion of censure, when it seemed it might win.
** Left alternatives

The poor performance of the LP in these parliaments led to two reactions on the left
- mass militancy, i.e. a rejection of parliamentary methods
- the 'eternal' left - pushing the LP to accept more radical policies. 'eternal' because
  reformist policies always involve compromise with capitalism 

Hardie, MacDonald and others resigned en mass from the ILP at the next vote that went against
them

MacDonald saw parliament as more important than the plight of the WC. This was exactly opposite
to Lenin's view that parliamentary activity as the lowest form of the workers movement.
** The outside left


Syndicalists recognized the inadequacy of parliament

The LP emerged from Liberalism due to the the union unrest beginning in 1910.
Union membership doubled, there were several national strikes, and clashes with police.
** A brake on the movement

The LP wasn't consulted over any union action. It frequently spoke against
atrikes, describing parliamentary activity as the only was for socialism, and even as
being truly revolutionary.

Labour MPs proposed a bill making it illegal to strike without going through a 30 day
conciliation process. The punishments were draconian fines. The TUC caused it to be dropped

In 1913 the LP and unions reconciled in their opposition to the miners strike. They were both
at risk from syndicalism. However syndicalism had no policies besides strikes for better pay/conditions.
* 3. War and reconstruction: Labour adopts socialism
** An early casualty of the fighting

MacDonald was replaced by Henderson after expressing doubts about the war

In 1915 the LP joined Asquith's coalition

Internationalism was abandoned, and workers leaders supported the war
** Moralism and Labour politics

Hardie discussed the idea of a general strike to prevent war, this was
defeated by the unions, making a rare foray into politics.

Internationalism was viewsed as a 'nice to have' by reformists, but expendable

The ILP remained opposed to the war, even after the coalition.
** The meaning of the split

The ILP opposed the war, as did Hardie, MacDonald and Snowden. Unions succumbed to patriotic hysteria - this was
an occasion when crisis allowed the union bureaucracy to impose its wishes
** The diverse attitudes to war

Pro-war views within the LP were extreme. ILP opponents were hounded, a mahjority of
objectors who were tries were ILP members.

The LP, unlike the SPD in Germany, didn't break up. This was because the bulk of its
support came from the unions, and so could absorb the range of opinions the unions had.
** The limits of the ILP position

The position of LP opponents to the war was based on the inefficiency of war - they viewed it
as a failing of diplomacy. By contrast Lenin viewed war as an inevitable consequence of capitalist
and imperialist competition

** Clydeside: the legend and the reality

A myth has grown connecting the Clyde Workers Committee and the Labour MPs
elected in 1922

Although there were strikes by the Clyde engineers, these weren't anti-war

** The triumph of statism

As a result of the war, the state took over most production. In return for their suspending rules on
working conditions, the union leadership began to work directly with the government

The upper reaches of the labour movement were absorbed by the state

** Reconstructing the party

Revolutionaries had grown in number as the LP collaborated during the war - these held
no truck with the LP. Discontent grew, and the 1917 revolution concentrated the LP's mind.

** 'Uncle Arthur' - apostle of Labour's socialist conversion

Lloyd George sent Arthur Henderson to Russia to bolster Russian support for the war.
He was horrified by what he saw, in particulae the elevation of workers over directors.

Fearing the return of large numbers of radicalised troops, skilled with arms, he looked
to Sidney Webb to help safeguard against "Bolshevism" via a strong parliamentary LP.

** The 1918 constitution: a quest for the 'people's party'

Henderson and Webb looked to reorganise the party so that it would speak for the
nation rather than the WC. Given over 90% of the party was affiliated trade unions
it was difficult to present this as beyond class.

The 1918 constitution created local Labour parties and individual membership

The ILP was sidelined as punishment for its pacifism

** Socialism at last

Webb and Henderson created Clause Four as a conscious attempt to fend off
revolution

At previous conferences attempts to write socialism into the constitution generally failed,
as even socialists feared the LP would lose votes if they did

Contradictory motions were allowed, even at the same conference - so it was no more than lip service

** Labour's new social order

This document called for a legal minimum wage, welfare provision, and other social improvements.

This was a logical consequence of their belief that suffering was an _unnecessary_ consequence
of capitalism.

The wide state power exerted during the war led them to believe in this

** Social reconstruction and nationalisation

The LP sought to manage capitalism through widespread nationalisation

This wasn't a particularly left-wing POV at the time, and in no way suggested
workers would actually be in control

Nationalisation would cement the power the unions had gained during WWI

Finally, it suited the reformist aim of piecemeal takeover of industry, but as Marks said, this would be
".. a reformation within the boundaries set by the bourgeoisie"

* 4. Riding the post-war storm
** Did Labour prevent a British revolution?
